### ISSUE TITLE
Latency?

### ISSUE THREAD

**Issue by rileydutton** [KillaMaaki/ReliableNetcode.NET#4]
Hey there,

I'm testing out using both ReliableNetcode.NET and your NetCodeIO.Net libraries in my project. The only issue I've run into so far that I haven't been able to solve, is that it seems like ReliableNetcode.NET is adding around 50ms of round-trip latency into the networking stack. So if I send a packet from my client to the server, if I respond as soon as I see it arrive on the NetCodeIO.Net layer, I'm seeing around 5-7ms latency. While when I wait for a response via ReliableNetcode.NET, it's closer to 50-60ms.

Is this additional latency part of the intended design? Or any idea what I could do to reduce it? I'm calling Update() as frequently as possible, and I've tried doing so on both a background thread and the main program thread, but no matter what I can't seem to shake that latency.

My project is being run via Mono on Linux if that makes a difference. Thanks!

**Comment by GlaireDaggers** [comment]
I'll investigate that 5-7ms latency on the weekend. I'm not super concerned about it, but it seems weird to me.

As for the 50-60ms latency, I think I just found a potential cause. Looks like a typo caused it to always engage congestion control mode, which throttles things down to only sending 10 packets per second.
I've pushed an update, check it out and see if that helps. There's still an overhead, though under good conditions this should top out at around 33ms (the send queue is processed around 30 times per second)

**Comment by rileydutton** [comment]
The 5-7ms latency is probably nothing to do with your end, that's probably just something with the way I'm doing stuff. I'm not concerned about it either.

I will test out the new code, thanks. Assuming that works, is there a way to increase the send queue process speed as a configuration variable? This program is solely responsible for sending/receiving packets so I'd like to do it more quickly if possible at the expense of CPU time. 

Thanks for the fast response!

**Comment by rileydutton** [comment]
That did fix that extra 50ms of latency. Thank you!
